
name: 'Terraform'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
         AWS_ACCESS_KEY_ID:${{secrets.AWS_ACCESS_KEY_ID}}
         AWS_SECRET_ACCESS__KEY_ID:${{secrets.AWS_SECRET_ACCESS_KEY_ID}}

 
    defaults:
      run:
        shell: bash

    
    - name: Checkout
      uses: actions/checkout@v3

    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
         terraform_version: 1.0.1
         terraform_wrapper: false
  

   
    - name: Terraform Init
      run: terraform init

    
    - name: Terraform Plan
      run: terraform plan -input=false
    
    - name: Terraform Apply
     
      run: terraform apply -auto-approve
